export const homeData = [
  {
    id: "1",
    name: "Dr. Areeb",
    verified: true,
    specialization: "Dermatologist",
    degree: "MBBS, Diploma in Dermatology",
    reviews: 130,
    experience: 2,
    isOnline: true,
    satisfaction: 99,
    phoneNo: "03051127342",
    tags: ["PRP", "Acne", "Hair Loss"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 1000,
        fastConfirm: false,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 1000,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Nov 28",
      },
    ],
    doctorStats: {
      waitTime: 10,
      averageTimeToPatient: 15,
      patientSatisfaction: 4.7,
      diagnosis: 4.8,
      staffBehaviour: 4.9,
      clinicEnv: 4.6,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "N",
        date: "15/07/2023",
        title: "I am satisfied with the doctor.",
        description:
          "Very well and understanding doctor. He gave satisfactory consultation. Hopefully medicine will affect too. Overall. Very well experience.",
        tags: [
          "10 min wait time",
          "Great Experience",
          "Good PA / Staff",
          "Good Clinic",
          "20 min meetup",
        ],
      },
      {
        id: 2,
        userInitial: "A",
        date: "02/09/2023",
        title: "Helped me with acne",
        description:
          "Great diagnosis. Acne reduced a lot after following his routine. Very polite and knowledgeable.",
        tags: ["Minimal wait", "Acne Treatment", "Polite Doctor"],
      },
      {
        id: 3,
        userInitial: "S",
        date: "10/10/2023",
        title: "PRP session went well",
        description: "Professional and explained every PRP step. Recommended!",
        tags: ["PRP Treatment", "Hygienic Clinic", "Friendly Staff"],
      },
    ],
  },

  {
    id: "2",
    name: "Dr. Hania Rehman",
    verified: true,
    specialization: "Psychologist",
    degree: "MS Clinical Psychology",
    reviews: 98,
    experience: 4,
    isOnline: false, 
    phoneNo: "0300-1234567",
    satisfaction: 96,
    tags: ["Anxiety", "Depression", "Therapy"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 1200,
        fastConfirm: true,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 1500,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Nov 30",
      },
    ],
    doctorStats: {
      waitTime: 6,
      averageTimeToPatient: 12,
      patientSatisfaction: 4.9,
      diagnosis: 4.7,
      staffBehaviour: 5,
      clinicEnv: 4.8,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "M",
        date: "12/08/2023",
        title: "Very comforting doctor",
        description:
          "She listens patiently and gives actionable advice. Really helped with my anxiety.",
        tags: ["Short wait time", "Calm Environment", "Therapy"],
      },
      {
        id: 2,
        userInitial: "R",
        date: "22/09/2023",
        title: "Amazing session",
        description:
          "Felt very relaxed after the session. She made me understand the root cause of my depression.",
        tags: ["Good Listener", "Friendly", "Productive Session"],
      },
    ],
  },

  {
    id: "3",
    name: "Dr. Zain Ahmad",
    isOnline: true,
    verified: true,
    specialization: "Cardiologist",
    degree: "MBBS, FCPS (Cardiology)",
    reviews: 215,
    experience: 7,
    phoneNo: "0300-1234567",
    satisfaction: 97,
    tags: ["Heart Checkup", "ECG", "Chest Pain"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: false,
    quickAppointments: [
      {
        type: "In-Person Consultation",
        price: 2000,
        fastConfirm: true,
        availableNow: true,
      },
    ],
    doctorStats: {
      waitTime: 12,
      averageTimeToPatient: 18,
      patientSatisfaction: 4.5,
      diagnosis: 4.6,
      staffBehaviour: 4.4,
      clinicEnv: 4.7,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "H",
        date: "04/10/2023",
        title: "Very expert doctor",
        description:
          "Doctor guided me very professionally regarding chest pain and ECG results.",
        tags: ["ECG", "Quick Checkup", "Expert"],
      },
      {
        id: 2,
        userInitial: "T",
        date: "18/10/2023",
        title: "Explained everything clearly",
        description:
          "He explained my heart condition in a very simple way. Highly satisfied.",
        tags: ["Clear Explanation", "No rush", "Good Clinic"],
      },
    ],
  },

  {
    id: "4",
    name: "Dr. Maira Khan",
    verified: false,
    isOnline: false,
    specialization: "Gynecologist",
    degree: "MBBS, FCPS (Gynecology)",
    reviews: 185,
    experience: 6,
    phoneNo: "0300-1234567",
    satisfaction: 98,
    tags: ["Pregnancy", "Ultrasound", "Women Health"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 900,
        fastConfirm: true,
        availableNow: false,
        fromDate: "Nov 29",
      },
      {
        type: "In-Person Consultation",
        price: 1500,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Dec 2",
      },
    ],
    doctorStats: {
      waitTime: 9,
      averageTimeToPatient: 10,
      patientSatisfaction: 4.8,
      diagnosis: 4.7,
      staffBehaviour: 4.9,
      clinicEnv: 4.6,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "J",
        date: "05/09/2023",
        title: "Very kind and humble",
        description:
          "I visited for pregnancy consultation. She was extremely helpful and guided me properly.",
        tags: ["Pregnancy", "Detailed Checkup", "Friendly Staff"],
      },
      {
        id: 2,
        userInitial: "A",
        date: "27/09/2023",
        title: "Good experience",
        description:
          "Ultrasound was done smoothly and doctor explained everything calmly.",
        tags: ["Ultrasound", "No long wait", "Clean Clinic"],
      },
    ],
  },

  {
    id: "5",
    name: "Dr. Hamza Tariq",
    verified: false,
    specialization: "Orthopedic Surgeon",
    degree: "MBBS, MS Orthopedics",
    reviews: 160,
    experience: 5,
    phoneNo: "0300-1234567",
    satisfaction: 95,
    tags: ["Back Pain", "Joint Pain", "Fractures"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: false,
    quickAppointments: [
      {
        type: "In-Person Consultation",
        price: 1800,
        fastConfirm: true,
        availableNow: true,
      },
    ],
    doctorStats: {
      waitTime: 14,
      averageTimeToPatient: 20,
      patientSatisfaction: 4.3,
      diagnosis: 4.4,
      staffBehaviour: 4.2,
      clinicEnv: 4.1,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "W",
        date: "13/07/2023",
        title: "Great for back pain",
        description:
          "My back pain improved significantly after following his exercise plan.",
        tags: ["Back Pain Relief", "Good Exercise Plan", "Quick Checkup"],
      },
      {
        id: 2,
        userInitial: "B",
        date: "08/09/2023",
        title: "Very knowledgeable",
        description:
          "He explained my joint issue very clearly. Highly recommended.",
        tags: ["Joint Pain", "Polite Doctor", "Professional"],
      },
    ],
  },

  {
    id: "6",
    name: "Dr. Naila Noor",
    verified: true,
    specialization: "Nutritionist",
    degree: "MS Human Nutrition",
    reviews: 142,
    experience: 3,
    phoneNo: "0300-1234567",
    satisfaction: 94,
    tags: ["Diet Plan", "Weight Loss", "Meal Prep"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 700,
        fastConfirm: true,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 900,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Dec 1",
      },
    ],
    doctorStats: {
      waitTime: 5,
      averageTimeToPatient: 9,
      patientSatisfaction: 4.6,
      diagnosis: 4.5,
      staffBehaviour: 1,
      clinicEnv: 4.8,
    },
    patientReviews: [
      {
        id: 1,
        userInitial: "F",
        date: "20/07/2023",
        title: "Perfect diet plan",
        description:
          "She made a customized diet plan according to my schedule. Lost 3kg in a month!",
        tags: ["Weight Loss", "Custom Diet", "Easy to Follow"],
      },
      {
        id: 2,
        userInitial: "K",
        date: "11/09/2023",
        title: "Very helpful",
        description:
          "I loved her meal prep strategy. Helped me stay consistent.",
        tags: ["Meal Prep", "Motivating Doctor", "Great Experience"],
      },
    ],
  },
];
