export  const homeData = [
  {
    id: "1",
    name: "Dr. Areeb",
    verified: true,
    specialization: "Dermatologist",
    degree: "MBBS, Diploma in Dermatology",
    reviews: 130,
    experience: 2,
    satisfaction: 99,
    tags: ["PRP", "Acne", "Hair Loss"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 1000,
        fastConfirm: true,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 1000,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Nov 28",
      },
    ],
  },

  {
    id: "2",
    name: "Dr. Hania Rehman",
    verified: true,
    specialization: "Psychologist",
    degree: "MS Clinical Psychology",
    reviews: 98,
    experience: 4,
    satisfaction: 96,
    tags: ["Anxiety", "Depression", "Therapy"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 1200,
        fastConfirm: true,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 1500,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Nov 30",
      },
    ],
  },

  {
    id: "3",
    name: "Dr. Zain Ahmad",
    verified: true,
    specialization: "Cardiologist",
    degree: "MBBS, FCPS (Cardiology)",
    reviews: 215,
    experience: 7,
    satisfaction: 97,
    tags: ["Heart Checkup", "ECG", "Chest Pain"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: false,
    quickAppointments: [
      {
        type: "In-Person Consultation",
        price: 2000,
        fastConfirm: true,
        availableNow: true,
      },
    ],
  },

  {
    id: "4",
    name: "Dr. Maira Khan",
    verified: true,
    specialization: "Gynecologist",
    degree: "MBBS, FCPS (Gynecology)",
    reviews: 185,
    experience: 6,
    satisfaction: 98,
    tags: ["Pregnancy", "Ultrasound", "Women Health"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 900,
        fastConfirm: true,
        availableNow: false,
        fromDate: "Nov 29",
      },
      {
        type: "In-Person Consultation",
        price: 1500,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Dec 2",
      },
    ],
  },

  {
    id: "5",
    name: "Dr. Hamza Tariq",
    verified: false,
    specialization: "Orthopedic Surgeon",
    degree: "MBBS, MS Orthopedics",
    reviews: 160,
    experience: 5,
    satisfaction: 95,
    tags: ["Back Pain", "Joint Pain", "Fractures"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: false,
    quickAppointments: [
      {
        type: "In-Person Consultation",
        price: 1800,
        fastConfirm: true,
        availableNow: true,
      },
    ],
  },

  {
    id: "6",
    name: "Dr. Naila Noor",
    verified: true,
    specialization: "Nutritionist",
    degree: "MS Human Nutrition",
    reviews: 142,
    experience: 3,
    satisfaction: 94,
    tags: ["Diet Plan", "Weight Loss", "Meal Prep"],
    profileImage: require("../assets/images/doc1.jpg"),
    canVideoCall: true,
    quickAppointments: [
      {
        type: "Video Consultation",
        price: 700,
        fastConfirm: true,
        availableNow: true,
      },
      {
        type: "In-Person Consultation",
        price: 900,
        fastConfirm: false,
        availableNow: false,
        fromDate: "Dec 1",
      },
    ],
  },
];